{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pizza_creation_latency_milliseconds",
     "legendFormat": "pizza creation latency"
    },
    { "expr": "request_latency_milliseconds", "legendFormat": "request latency" }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "TOTAL" },
    {
     "expr": "rate(http_requests_post_total[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(http_requests_put_total[1m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(http_requests_delete_total[1m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(http_requests_get_total[1m])",
     "legendFormat": "GET"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "auth_successful_total", "legendFormat": "success" },
    { "expr": "auth_failed_total", "legendFormat": "failure" }
   ]
  },
  {
   "title": "CPU and Memory Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "CPU" },
    { "expr": "memory_usage_percent", "legendFormat": "Memory" }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pizza_revenue_dollars_total", "legendFormat": "Revenue" }
   ]
  },
  {
   "title": "Pizzas",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(pizzas_sold_total[1m])", "legendFormat": "Pizza Purchases" },
    { "expr": "pizza_creation_failures_total", "legendFormat": "Creation Failure" }
   ]
  }
 ]
}